//! # Lyrebird - Pluggable Transport Proxy Applications
//!
//! This crate provides a PT-manager loop usable as a library
//! (`lyrebird::run()`) or as a standalone binary that implements the
//! Tor pluggable-transport spec on top of the [`ptrs`] interface.
//!
//! **Stability**: the public API is unstable and subject to change
//! without notice; do not rely on this crate for security-critical
//! applications. The server-side path is incomplete and gated behind
//! the `experimental-server` cargo feature — it must not be enabled in
//! production.
//!
//! ## Lyrebird Pluggable Transport Bridge
//!
//! ['lyrebird'] provides an executable program designed to manage the calling
//! interface used by the Tor libraries when launching pluggable transports (see `pt-spec.txt`).
//!
//! `... [tor_client] <---> [pt_client] <====> [pt_bridge] <---> [tor_orport] ...`
//!
//! Usage info:
//!
//! ```txt
//! Tunnel Tor SOCKS5 traffic through pluggable transport connections
//!
//! Usage: lyrebird [OPTIONS]
//!
//! Options:
//!       --enable-logging         Log to {TOR_PT_STATE_LOCATION}/obfs4proxy.log
//!       --log-level <LOG_LEVEL>  Log Level (ERROR/WARN/INFO/DEBUG/TRACE) [default: ERROR]
//!       --unsafe-logging         Disable the address scrubber on logging
//!   -h, --help                   Print help
//!   -V, --version                Print version
//! ```
//!
//! ### Installation
//!
//! To install:
//!
//! `cargo install lyrebird`
//!
//! This installs in the configured Rust location (i.e. `$HOME/.cargo/bin`). You may
//! wish to copy `./lyrebird` to a permanent location (e.g. `/usr/local/bin`).
//!
//! Client side torrc configuration:
//! ```text
//! ClientTransportPlugin obfs4 exec /usr/local/bin/lyrebird
//! ```
//!
//! Bridge side torrc configuration:
//! ```text
//! # Act as a bridge relay.
//! BridgeRelay 1
//!
//! # Enable the Extended ORPort
//! ExtORPort auto
//!
//! # Use lyrebird to provide the obfs4 protocol.
//! ServerTransportPlugin obfs4 exec /usr/local/bin/lyrebird
//!
//! # (Optional) Listen on the specified address/port for obfs4 connections as
//! # opposed to picking a port automatically.
//! #ServerTransportListenAddr obfs4 0.0.0.0:443
//! ```
//!
//! ### Tips and tricks
//!
//!  * On modern Linux systems it is possible to have lyrebird bind to reserved
//!    ports (<=1024) even when not running as root by granting the
//!    `CAP_NET_BIND_SERVICE` capability with setcap:
//!
//!    `# setcap 'cap_net_bind_service=+ep' /usr/local/bin/lyrebird`
//!
//!  * The autogenerated obfs4 bridge parameters are placed in
//!    `DataDir/pt_state/obfs4_state.json`.  To ease deployment, the client side
//!    bridge line is written to `DataDir/pt_state/obfs4_bridgeline.txt`.
//!
// Follow-up work tracked in the issue tracker, not in rustdoc:
//   - tunnel-level metrics (failures, byte counters).
//   - rate-limiting for the bidirectional copy.
//   - replace `tokio::io::copy_bidirectional` with an interactive copy
//     that flushes only when the reader stalls.

#![deny(missing_docs)]

use obfs4::Obfs4PT;
use ptrs::{error, info, warn, PluggableTransport};

use anyhow::{anyhow, Context, Result};
use clap::Parser;
use fast_socks5::util::target_addr::TargetAddr;
use safelog::sensitive;
#[cfg(feature = "experimental-server")]
use tokio::sync::oneshot;
use tokio::sync::Semaphore;
use tokio::task::JoinSet;
use tokio::{
    io::{copy_bidirectional, AsyncRead, AsyncWrite, AsyncWriteExt},
    net::{TcpListener, TcpStream},
};
use tokio_util::sync::CancellationToken;
use tracing::Level;
use tracing_subscriber::{filter::LevelFilter, prelude::*};

use std::{net::SocketAddr, pin::Pin, str::FromStr, sync::Arc, time::Duration};

/// Maximum number of concurrently handled client connections. This is also
/// the size of the lifecycle permit pool: every in-flight connection task
/// holds one permit for its whole lifetime, so "all permits available" is
/// an exact zero-active-tasks signal for shutdown (DoS mitigation included).
const MAX_CONCURRENT_CONNS: usize = 1024;

/// Grace period a soft interrupt (first SIGINT / Ctrl+C) gives to
/// already-established connections: they may finish on their own before
/// the remainder is force-cancelled. Bounded so `run()` always returns.
const DRAIN_GRACE: Duration = Duration::from_secs(15);

/// Upper bound on the final wait AFTER in-flight connections are
/// force-cancelled. Connection tasks watch the cancellation token at their
/// next await point, so this only guards a task wedged inside a
/// non-cancellable section; it is not the normal teardown duration.
const FORCE_GRACE: Duration = Duration::from_secs(5);

/// Client Socks address to listen on.
const CLIENT_SOCKS_ADDR: &str = "127.0.0.1:0";

/// Error defined to denote a failure to get the bridge line
#[derive(Debug, thiserror::Error)]
#[error("Error while obtaining bridge line data")]
struct BridgeLineParseError;

#[derive(Parser)]
#[command(author, version, long_about = None, about="Tunnel Tor SOCKS5 traffic through pluggable transport connections")]
struct Args {
    /// Log to {TOR_PT_STATE_LOCATION}/obfs4proxy.log
    #[arg(long, default_value_t = false)]
    enable_logging: bool,

    /// Log Level (ERROR/WARN/INFO/DEBUG/TRACE)
    #[arg(long, default_value_t=String::from("ERROR"))]
    log_level: String,

    /// Disable the address scrubber on logging
    #[arg(long, default_value_t = false)]
    unsafe_logging: bool,
}

/// initialize the logging receiver(s) for things to be logged into using the
/// tracing / tracing_subscriber libraries
// TODO: GeoIP. Json for file log writer.
fn init_logging_recvr(
    enable: bool,
    should_scrub: bool,
    level_str: &str,
    statedir: &str,
) -> Result<()> {
    if should_scrub {
        let _ = safelog::enforce_safe_logging();
    } else {
        let _ = safelog::disable_safe_logging();
    }

    // The PT protocol owns stdout for the parent ↔ PT control channel.
    // Logs go to stderr; the file layer below (when enabled) writes
    // separately into the state directory.
    //
    // Compact (single-line) layout matches the parent process's
    // tracing-subscriber default — we share a terminal with it when
    // launched via the busybox dispatch, so consistent formatting
    // matters more than the pretty multi-line output. Per-target
    // filter mutes the chatty `fast_socks5` connection log; arti is
    // the one bashing through dozens of PT connections during
    // bootstrap and the per-conn lines drown the relevant signal.
    let console_filter =
        tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| {
            tracing_subscriber::EnvFilter::new(
                "info,fast_socks5=warn,obfs4::sessions=warn,lyrebird::handshake=info",
            )
        });
    // Honor the https://no-color.org convention: any (even empty) NO_COLOR
    // disables ANSI. We're normally launched as a PT child by the parent
    // process's busybox dispatch and inherit its environment, so the parent
    // can propagate its own color preference by setting NO_COLOR before
    // spawning us — without that, this layer defaulted to ANSI-always-on
    // regardless of the parent's own logging config.
    let ansi = std::env::var_os("NO_COLOR").is_none();
    let console_layer = tracing_subscriber::fmt::layer()
        .with_ansi(ansi)
        .with_writer(std::io::stderr)
        .with_filter(console_filter);

    let log_layers = if enable {
        let level = Level::from_str(level_str)?;

        let file = std::fs::File::create(format!("{statedir}/obfs4proxy.log"))?;

        let state_dir_layer = tracing_subscriber::fmt::layer()
            .with_writer(file)
            .with_filter(LevelFilter::from_level(level));

        console_layer.and_then(state_dir_layer).boxed()
    } else {
        console_layer.boxed()
    };

    tracing_subscriber::registry().with(log_layers).init();

    Ok(())
}

/// Resolve a `fast_socks5::util::TargetAddr` to a concrete `SocketAddr`.
/// `Ip(_)` variants pass through; `Domain` variants always fail because
/// the PT spec forbids the transport from doing DNS — that's the calling
/// Tor client's responsibility.
pub fn resolve_target_addr(addr: &TargetAddr) -> Result<SocketAddr> {
    match addr {
        TargetAddr::Ip(sa) => Ok(*sa),
        TargetAddr::Domain(_, _) => {
            // this will always fail because ptrs does not do dns lookups.
            ptrs::resolve_addr(format!("{addr}")).context("domain resolution failed")
        }
    }
}

/// Dial a bridge's OR-port and apply socket options that keep the obfs4
/// carrier connection healthy:
///   * `TCP_NODELAY` — obfs4 frames are small and latency-sensitive; Nagle
///     coalescing only hurts.
///   * TCP keepalive — an obfs4 carrier can sit briefly idle (e.g. while a
///     one-hop directory circuit for a bridge descriptor is being built).
///     Without keepalive such an idle carrier is liable to be silently reaped
///     by the OS, a NAT, or a local LSP/proxy shim, surfacing as os error
///     10053 ("connection aborted by the software in your host machine") and
///     tearing the bridge channel down mid-bootstrap. C-tor keeps its single
///     bridge connection alive at the Tor layer; we make the carrier itself
///     resilient instead.
async fn dial_bridge(remote_addr: SocketAddr) -> std::io::Result<TcpStream> {
    let stream = TcpStream::connect(remote_addr).await?;
    // Best-effort: failure to set an option must not abort the dial.
    let _ = stream.set_nodelay(true);
    let keepalive = socket2::TcpKeepalive::new()
        .with_time(std::time::Duration::from_secs(15))
        .with_interval(std::time::Duration::from_secs(15));
    let _ = socket2::SockRef::from(&stream).set_tcp_keepalive(&keepalive);
    Ok(stream)
}

/// Run the lyrebird pluggable transport. Expects the standard
/// `TOR_PT_*` environment variables set by the parent process (arti /
/// tor) and speaks the PT-managed-transport protocol on stdin/stdout.
///
/// # Upstream proxies
///
/// Client setup is *fail-closed* with respect to `TOR_PT_PROXY`
/// (PT-spec §3.3.2): no upstream proxy dialer is implemented, so a
/// configured upstream proxy is answered with `PROXY-ERROR` on the
/// control channel and setup aborts before any transport starts. The
/// parent is never told the proxy is in use when it is not.
///
/// # Shutdown semantics
///
/// `run()` owns every task it spawns — the accept loops, every
/// per-connection task, and the stdin watcher — and does not return while
/// any of them is still alive in the ambient runtime:
///
/// * terminate (`SIGTERM` / Ctrl+Break) or parent EOF
///   (`TOR_PT_EXIT_ON_STDIN_CLOSE=1`): in-flight connections are
///   cancelled immediately and awaited, bounded by [`FORCE_GRACE`].
/// * interrupt (`SIGINT` / Ctrl+C): accepting stops first, then in-flight
///   connections get [`DRAIN_GRACE`] to finish on their own; whatever is
///   still alive after the budget is cancelled and awaited. A second
///   interrupt or a parent EOF during the drain escalates to the
///   immediate teardown.
/// * all listeners ended on their own ("proxy closed"): handled like an
///   interrupt, so tunnel tasks are never left behind.
///
/// # Cancel safety
///
/// This function is **not cancel-safe**. It manages long-lived server
/// state and open connections. The guarantees above hold only when the
/// future is driven to completion; dropping it abandons all active
/// tunnels without any shutdown.
pub async fn run() -> Result<()> {
    let args = Args::parse();

    // Make state directory
    let statedir = ptrs::make_state_dir()?;

    // launch tracing subscriber with filter level
    init_logging_recvr(
        args.enable_logging,
        !args.unsafe_logging,
        &args.log_level,
        &statedir,
    )?;

    // Everything this run() invocation owns hangs off `ctx`: the shutdown
    // tokens for the two teardown phases and the lifecycle permit pool
    // every connection task holds a permit from.
    let ctx = RunTasks::new();

    // PT-spec §3.4 ("Feature #15435"): when the parent process sets
    // `TOR_PT_EXIT_ON_STDIN_CLOSE=1` it signals "stop" by closing our
    // stdin — that's the canonical managed-PT shutdown path arti's
    // ptmgr uses when a transport is removed/reconfigured. Watch stdin
    // in the background and fire `parent_died` on EOF so the main loop
    // below can exit promptly. The watcher is owned like every other
    // task: `stop_accepting` cancels it, so it never outlives run().
    // When the env var is not set the watcher is not spawned and the
    // token never fires, preserving the previous "ignore stdin" behavior
    // exactly.
    let parent_died = tokio_util::sync::CancellationToken::new();
    if ptrs::pt_should_exit_on_stdin_close() {
        let parent_died = parent_died.clone();
        let watcher_off = ctx.stdin_watcher.clone();
        tokio::spawn(async move {
            tokio::select! {
                // run() is shutting down: stop watching, don't fire.
                _ = watcher_off.cancelled() => {}
                _ = ptrs::wait_stdin_close() => parent_died.cancel(),
            }
        });
    }

    // launch runners
    let mut listeners: JoinSet<Result<()>> = if ptrs::is_client()? {
        // running as CLIENT — run() owns the returned accept-loop tasks.
        client_setup(&statedir, ctx.clone()).await?
    } else {
        // running as SERVER
        //
        // Server-side is gated behind `experimental-server` because the PT
        // handshake is not yet wired and the ExtORPort dial is missing.
        // Without the feature we refuse to start rather than silently
        // exposing an unauthenticated proxy.
        #[cfg(feature = "experimental-server")]
        {
            let rx = server_setup(&statedir, ctx.accept.clone()).await?;
            // The experimental server still reports "all listeners gone"
            // through its legacy oneshot channel; adopt that channel into
            // the same task set the client uses so every shutdown path
            // below treats both roles uniformly. (server_setup's internal
            // accept loops stay feature-gated legacy — the server side is
            // incomplete by design.)
            let mut set = JoinSet::new();
            set.spawn(async move {
                rx.await
                    .map_err(|e| anyhow!("server exit channel closed: {e}"))?;
                Ok(())
            });
            set
        }
        #[cfg(not(feature = "experimental-server"))]
        {
            return Err(anyhow!(
                "lyrebird server-side is not implemented; rebuild with \
                 `--features experimental-server` for development use only"
            ));
        }
    };

    info!("accepting connections");

    // The pt config protocol is finished, and incoming connections are
    // processed by the owned accept loops. Wait till the parent dies
    // (immediate exit), a SIGTERM / Ctrl+Break is received (immediate
    // exit), a SIGINT / Ctrl+C is received (graceful drain), or every
    // listener task ends on its own ("proxy closed").
    let exit = loop {
        tokio::select! {
            maybe = listeners.join_next() => match maybe {
                // The set is empty: every listener has ended. (Previously
                // this was reported through a oneshot fired by a detached
                // monitor task that run() did not own.)
                None => break ExitKind::ProxyClosed,
                // One of several listeners ended: log it — both failure
                // levels — and keep serving on the rest.
                Some(res) => log_listener_result(res),
            },
            sig = shutdown_signal() => {
                if sig.is_terminate() {
                    info!("proxy terminated");
                    break ExitKind::Terminate;
                }
                break ExitKind::Interrupt;
            }
            // `parent_died` only fires when TOR_PT_EXIT_ON_STDIN_CLOSE=1
            // was set AND the parent closed our stdin. When the env var is
            // unset the watcher is never spawned and this branch is
            // pending forever.
            _ = parent_died.cancelled() => break ExitKind::ParentClosedStdin,
        }
    };

    // ---- unified teardown: every exit path ends here --------------------
    // Phase 1 on all paths: stop accepting and release the auxiliary
    // watcher, so no new work can appear while we are shutting down.
    ctx.stop_accepting();
    match exit {
        ExitKind::Interrupt => {
            info!("received interrupt, shutting down");
            join_accept_loops(&mut listeners).await;
            // Soft teardown: give current transfers the budget to finish on
            // their own, escalating on a second interrupt or parent EOF.
            let drained = tokio::select! {
                drained = drain_connections(&ctx, DRAIN_GRACE) => drained,
                _ = shutdown_signal() => {
                    info!("second interrupt; cancelling remaining connections");
                    false
                }
                _ = parent_died.cancelled() => {
                    info!("parent process closed stdin during shutdown; cancelling remaining connections");
                    false
                }
            };
            if !drained {
                cancel_connections(&ctx).await;
            }
        }
        ExitKind::ProxyClosed => {
            info!("proxy closed");
            join_accept_loops(&mut listeners).await;
            if !drain_connections(&ctx, DRAIN_GRACE).await {
                info!("drain budget elapsed; cancelling remaining connections");
                cancel_connections(&ctx).await;
            }
        }
        // Terminate / parent EOF mean "exit now": cancel in-flight
        // connections first, then join the accept loops. Both waits are
        // bounded, so run() always actually returns.
        ExitKind::Terminate | ExitKind::ParentClosedStdin => {
            cancel_connections(&ctx).await;
            join_accept_loops(&mut listeners).await;
        }
    }
    // Every task this run() spawned has now been joined (or bounded-force
    // finished): the listener set is empty and all lifecycle permits are
    // back, so nothing owned by run() survives in the caller's runtime.
    debug_assert_eq!(
        ctx.lifecycle.available_permits(),
        MAX_CONCURRENT_CONNS,
        "connection tasks still in flight after shutdown"
    );

    Ok(())
}

/// Which branch of run()'s main wait loop ended the service phase. Selects
/// the teardown style on the unified exit path below.
#[derive(Clone, Copy)]
enum ExitKind {
    /// Every listener task has ended on its own.
    ProxyClosed,
    /// First SIGINT / Ctrl+C: graceful drain of in-flight connections.
    Interrupt,
    /// SIGTERM / Ctrl+Break: immediate teardown.
    Terminate,
    /// Parent closed our stdin (TOR_PT_EXIT_ON_STDIN_CLOSE=1 was set).
    ParentClosedStdin,
}

/// Everything one [`run()`] invocation owns, shared with the tasks it
/// spawns: one cancellation token per teardown phase, plus the lifecycle
/// permit pool that doubles as the connection-admission cap.
///
/// Shutdown runs in two phases:
///
/// 1. [`RunTasks::stop_accepting`] — synchronous; fires `accept` and
///    `stdin_watcher` so no new connection task can appear and no
///    auxiliary task outlives `run()`.
/// 2. either a graceful drain (in-flight tunnels finish on their own,
///    observed through [`RunTasks::wait_idle`] under a finite timeout) or
///    a forced teardown (`conns` fired; each connection wrapper drops its
///    tunnel at its next await point).
#[derive(Clone)]
struct RunTasks {
    /// Phase-1 token: cancelled first on EVERY shutdown path. Accept loops
    /// break out of their accept loop when it fires.
    accept: CancellationToken,
    /// Phase-2 token: tears down in-flight connection tasks. Fired
    /// immediately on terminate/EOF; only after the drain budget expires
    /// on a soft interrupt.
    conns: CancellationToken,
    /// Cancels the stdin watcher spawned under
    /// `TOR_PT_EXIT_ON_STDIN_CLOSE=1`, so no auxiliary task survives
    /// `run()`.
    stdin_watcher: CancellationToken,
    /// Admission + lifecycle pool of [`MAX_CONCURRENT_CONNS`] permits:
    /// every in-flight connection task holds exactly one for its lifetime,
    /// which makes the pool an exact in-flight-connection counter.
    lifecycle: Arc<Semaphore>,
}

impl RunTasks {
    fn new() -> Self {
        Self {
            accept: CancellationToken::new(),
            conns: CancellationToken::new(),
            stdin_watcher: CancellationToken::new(),
            lifecycle: Arc::new(Semaphore::new(MAX_CONCURRENT_CONNS)),
        }
    }

    /// Phase 1 of every shutdown path: stop taking new connections and
    /// release the auxiliary stdin watcher. Synchronous: after this
    /// returns, no new connection task can be spawned.
    fn stop_accepting(&self) {
        self.accept.cancel();
        self.stdin_watcher.cancel();
    }

    /// Resolves exactly when no connection task is in flight: each
    /// in-flight connection holds one lifecycle permit, so acquiring the
    /// whole pool succeeds only once all of them are back. Cancel-safe;
    /// the acquired (empty) permit bundle is dropped immediately, and no
    /// new task can appear because `accept` is cancelled before any
    /// caller awaits this.
    async fn wait_idle(&self) {
        let _ = self
            .lifecycle
            .acquire_many(u32::try_from(MAX_CONCURRENT_CONNS).expect("permit count fits u32"))
            .await;
    }
}

/// Graceful teardown phase: wait up to `budget` for in-flight connections
/// to finish on their own. Returns `true` when every connection task ended
/// within the budget, `false` when the budget expired and the remainder
/// must be force-cancelled.
async fn drain_connections(ctx: &RunTasks, budget: Duration) -> bool {
    tokio::time::timeout(budget, ctx.wait_idle()).await.is_ok()
}

/// Forced teardown phase: cancel every in-flight connection, then wait —
/// bounded by [`FORCE_GRACE`] — until each has released its lifecycle
/// permit. Connection wrappers watch the token with a biased `select!`, so
/// this normally resolves in milliseconds; the bound only covers a task
/// wedged inside a non-cancellable section.
async fn cancel_connections(ctx: &RunTasks) {
    ctx.conns.cancel();
    let _ = tokio::time::timeout(FORCE_GRACE, ctx.wait_idle()).await;
}

/// Log the completion of one accept-loop task, surfacing BOTH failure
/// levels: the outer [`tokio::task::JoinError`] (the task panicked or was
/// aborted) and the accept loop's own `Err` (e.g. a fatal accept error) —
/// neither may be swallowed silently.
fn log_listener_result(res: std::result::Result<Result<()>, tokio::task::JoinError>) {
    match res {
        Ok(Ok(())) => info!("listener stopped"),
        Ok(Err(e)) => warn!("listener failed: {e:#}"),
        Err(join) => warn!("listener task aborted: {join}"),
    }
}

/// Join every remaining accept loop in the set, logging each result (both
/// failure levels — see [`log_listener_result`]).
async fn join_accept_loops(listeners: &mut JoinSet<Result<()>>) {
    while let Some(res) = listeners.join_next().await {
        log_listener_result(res);
    }
}

/// Cross-platform shutdown-signal helper. On Unix maps `SIGTERM` →
/// `Terminate`, `SIGINT` → `Interrupt`. On Windows uses
/// `Ctrl+Break` → `Terminate`, `Ctrl+C` → `Interrupt`.
#[derive(Clone, Copy)]
enum Shutdown {
    Interrupt,
    Terminate,
}

impl Shutdown {
    fn is_terminate(self) -> bool {
        matches!(self, Shutdown::Terminate)
    }
}

#[cfg(unix)]
async fn shutdown_signal() -> Shutdown {
    use tokio::signal::unix::{signal, SignalKind};
    let mut sigint = signal(SignalKind::interrupt()).expect("install SIGINT handler");
    let mut sigterm = signal(SignalKind::terminate()).expect("install SIGTERM handler");
    tokio::select! {
        _ = sigterm.recv() => Shutdown::Terminate,
        _ = sigint.recv() => Shutdown::Interrupt,
    }
}

#[cfg(not(unix))]
async fn shutdown_signal() -> Shutdown {
    use tokio::signal::windows::{ctrl_break, ctrl_c};
    let mut c_c = ctrl_c().expect("install Ctrl+C handler");
    let mut c_break = ctrl_break().expect("install Ctrl+Break handler");
    tokio::select! {
        _ = c_break.recv() => Shutdown::Terminate,
        _ = c_c.recv() => Shutdown::Interrupt,
    }
}

// ================================================================ //
//                            Client                                //
// ================================================================ //

async fn client_setup(_statedir: &str, ctx: RunTasks) -> Result<JoinSet<Result<()>>> {
    let obfs4_name = Obfs4PT::name();
    let webtunnel_name = webtunnel::WEBTUNNEL_NAME.to_string();

    // PT spec §3.3.1: announce our protocol version to the parent before
    // anything else the parent parses on the control channel.
    pt_proto::print_version();

    // PT-spec §3.3.2, fail-closed: when the parent sets TOR_PT_PROXY, ALL
    // outgoing traffic MUST be routed through that upstream proxy, and the
    // PT must answer with either `PROXY DONE` (proxy supported and
    // actually in use) or `PROXY-ERROR` and terminate — before any
    // transport is initialized. There is no upstream proxy dialer in this
    // codebase: `dial_bridge` always opens a *direct* TCP connection, and
    // the requested URI used to be dropped on the floor (`_proxy_uri`).
    // Proceeding silently would route traffic around the configured proxy
    // while the parent believes its routing requirement is honored, and
    // answering `PROXY DONE` would promise a route the code never uses.
    //
    // The gate therefore tests the raw variable BEFORE the core `TOR_PT_*`
    // reader: ANY set (non-empty) value is refused outright — even a URI
    // the reader would reject must be answered on the control channel with
    // `PROXY-ERROR`, not with the reader's bare exit. An empty value means
    // "no upstream proxy requested", matching the reference PT
    // implementations. Either way the parent sees the transport fail to
    // configure instead of believing its proxy is in use.
    let proxy_requested = std::env::var_os(ptrs::constants::PROXY)
        .map(|value| value.to_string_lossy().into_owned())
        .filter(|value| !value.is_empty());
    if let Some(proxy_uri) = proxy_requested {
        let reason = format!(
            "upstream proxy dialing is not supported by this transport; refusing to connect directly instead of via {proxy_uri}"
        );
        pt_proto::print_proxy_error(&reason);
        return Err(anyhow!(
            "TOR_PT_PROXY={proxy_uri} is set but upstream proxy dialing is not implemented; refusing to bypass the configured proxy (PT-spec fail-closed)"
        ));
    }

    // TOR_PT_PROXY is guaranteed unset or empty from here on (fail-closed
    // check above). The per-connection `proxy_uri` plumbing stays inert;
    // it is kept as the seam a future upstream proxy-dialer would attach
    // to.
    let client_pt_info = ptrs::ClientInfo::new()?;
    let proxy_uri = url::Url::parse("data:,").expect("placeholder url");

    // Every accept loop goes into the set returned to the caller: `run()`
    // owns these tasks and joins them on every exit path, so no listener —
    // and no connection a listener spawned — can outlive `run()` in the
    // ambient runtime.
    let mut listeners: JoinSet<Result<()>> = JoinSet::new();

    for name in client_pt_info.methods {
        info!(name);

        if name == obfs4_name {
            let builder = Obfs4PT::client_builder();
            let listener = tokio::net::TcpListener::bind(CLIENT_SOCKS_ADDR).await?;
            let local_addr = listener.local_addr()?;
            pt_proto::print_cmethod(&name, "socks5", local_addr);
            listeners.spawn(client_accept_loop(
                listener,
                builder,
                proxy_uri.clone(),
                ctx.clone(),
            ));
        } else if name == webtunnel_name {
            let builder = webtunnel::WebTunnelBuilder::default();
            let listener = tokio::net::TcpListener::bind(CLIENT_SOCKS_ADDR).await?;
            let local_addr = listener.local_addr()?;
            pt_proto::print_cmethod(&name, "socks5", local_addr);
            listeners.spawn(client_accept_loop(
                listener,
                builder,
                proxy_uri.clone(),
                ctx.clone(),
            ));
        } else {
            pt_proto::print_cmethod_error(&name, "no such transport is supported");
            warn!("no such transport is supported");
            continue;
        }
    }

    // PT spec §3.3.3: end of method announcements.
    pt_proto::print_cmethods_done();

    Ok(listeners)
}

async fn connection_permit(
    semaphore: Arc<tokio::sync::Semaphore>,
    cancel: &CancellationToken,
) -> Option<tokio::sync::OwnedSemaphorePermit> {
    tokio::select! {
        biased;
        _ = cancel.cancelled() => None,
        permit = semaphore.acquire_owned() => permit.ok(),
    }
}

async fn client_accept_loop<C>(
    listener: TcpListener,
    builder: impl ptrs::ClientBuilder<TcpStream, ClientPT = C> + Send + 'static,
    proxy_uri: url::Url,
    ctx: RunTasks,
) -> Result<()>
where
    // the provided client builder should build the C ClientTransport.
    C: ptrs::ClientTransport<TcpStream, std::io::Error> + Send + 'static,
{
    let pt_name = C::method_name();
    loop {
        tokio::select! {
            _ = ctx.accept.cancelled() => {
                info!("{pt_name} received shutdown signal");
                break; // exit the loop so graceful shutdown actually stops accepting
            }
            res = listener.accept() => {
                let (conn, client_addr) = match res {
                    Err(e) => {
                        error!("failed to accept tcp connection {e}");
                        break;
                    }
                    Ok(c) => c,
                };
                // Acquire a lifecycle permit before spawning: it doubles as
                // the concurrency cap and the task-lifetime marker that
                // `RunTasks::wait_idle` counts, so shutdown always knows
                // exactly how many connections are still in flight.
                let permit = match connection_permit(Arc::clone(&ctx.lifecycle), &ctx.accept).await {
                    Some(p) => p,
                    None => break,
                };
                let builder_clone = builder.clone();
                let proxy_clone = proxy_uri.clone();
                let conns = ctx.conns.clone();
                tokio::spawn(async move {
                    let _permit = permit; // held for the task's lifetime, freed on drop
                    tokio::select! {
                        biased;
                        // Forced teardown: dropping this future drops both
                        // halves of the tunnel. Runs only once the graceful
                        // drain budget expired (or on terminate/EOF).
                        _ = conns.cancelled() => {}
                        res = client_handle_connection(conn, builder_clone, proxy_clone, client_addr) => {
                            if let Err(e) = res {
                                warn!(
                                    address = sensitive(client_addr).to_string(),
                                    "connection task failed: {e:#}"
                                );
                            }
                        }
                    }
                });
            }
        }
    }

    Ok(())
}

/// This function assumes that the provided connection / socket manages reconstruction
/// and reliability before passing to this layer.
async fn client_handle_connection<In, C, B>(
    conn: In,
    mut builder: B,
    _proxy_uri: url::Url,
    client_addr: SocketAddr,
) -> Result<()>
where
    // the provided T must be usable as a connection in an async context
    In: AsyncRead + AsyncWrite + Send + Unpin,
    // the provided client builder should build the C ClientTransport.
    C: ptrs::ClientTransport<TcpStream, std::io::Error> + Send,
    B: ptrs::ClientBuilder<TcpStream, ClientPT = C>,
{
    // PT-spec §3.5 requires the parent to negotiate USERNAME/PASSWORD
    // (auth method 0x02) and pack the per-bridge PT arguments into the
    // UNAME/PASSWD fields. We accept any creds (and also accept clients
    // that legitimately want NO_AUTH) — see `PtArgsAuth` below.
    let mut config =
        fast_socks5::server::Config::<fast_socks5::server::DenyAuthentication>::default()
            .with_authentication(PtArgsAuth);
    config.set_allow_no_auth(true);
    // Critical: we are a pluggable transport, not a plain TCP proxy. With
    // the default `execute_command = true`, `upgrade_to_socks5()` would
    // itself open a *plain* TCP connection to the bridge, send the SOCKS
    // reply, and proxy the parent against that — bypassing obfs4 entirely
    // and consuming the parent socket. We must only *read* the request
    // here and do the obfs4 dial + reply ourselves below.
    config.set_execute_command(false);
    let socks5_conn = fast_socks5::server::Socks5Socket::new(conn, Arc::new(config));

    let mut socks5_conn = socks5_conn.upgrade_to_socks5().await?;
    let creds = socks5_conn.take_credentials();

    let target_addr = socks5_conn
        .target_addr()
        .ok_or(BridgeLineParseError)
        .context("missing remote address in request")?;

    // Reconstruct the PT-spec argument string from SOCKS5 user/pass and
    // hand it to the transport's `options(&Args)` so the obfs4
    // ClientBuilder picks up `cert=...` / `iat-mode=...` etc.
    let arg_string = arg_string_from_creds(creds);
    let args = if arg_string.is_empty() {
        ptrs::args::Args::default()
    } else {
        ptrs::args::Args::from_str(&arg_string).context("parsing PT arg string")?
    };
    <B as ptrs::ClientBuilder<TcpStream>>::options(&mut builder, &args)
        .map_err(|e| anyhow::anyhow!("applying PT args to builder: {e}"))?;

    let remote_addr = resolve_target_addr(target_addr).context("no remote address")?;

    // The outgoing OR-port dial. Boxing it as a `FutureResult` is the seam
    // exercised by tests: `establish_pt_conn` only ever sees a pinned
    // future yielding the underlying socket, so an in-memory
    // `tokio::io::duplex()` half can stand in for the real `TcpStream`.
    let remote: Pin<ptrs::FutureResult<TcpStream, std::io::Error>> =
        Box::pin(dial_bridge(remote_addr));

    // build the pluggable transport client and then dial, completing the
    // connection and handshake when the future is await-ed.
    let pt_client = builder.build();
    let mut pt_conn = establish_pt_conn(pt_client, remote, client_addr).await?;

    // The obfs4 tunnel to the bridge is up, so report CONNECT success to
    // the PT parent (arti/tor). Because we disabled `execute_command`,
    // fast-socks5 has NOT sent any reply — we must. This is the canonical
    // SOCKS5 success frame: VER=5, REP=0 (succeeded), RSV=0, ATYP=1
    // (IPv4), BND.ADDR=0.0.0.0, BND.PORT=0. The parent ignores BND.*.
    let mut parent = socks5_conn.into_inner();
    parent
        .write_all(&[0x05, 0x00, 0x00, 0x01, 0, 0, 0, 0, 0, 0])
        .await
        .context("writing SOCKS5 success reply to PT parent")?;
    parent
        .flush()
        .await
        .context("flushing SOCKS5 success reply")?;

    if let Err(e) = copy_bidirectional(&mut parent, &mut pt_conn).await {
        warn!(
            addres = sensitive(client_addr).to_string(),
            "tunnel closed with error: {e:#?}"
        );
    }
    Ok(())
}

/// Drive a built pluggable-transport client to completion against a dial
/// future, returning the wrapped tunnel stream.
///
/// This is the outgoing-connection seam carved out of
/// [`client_handle_connection`]. The dial is supplied as an already-pinned
/// [`ptrs::FutureResult`] (the same shape `establish` consumes) rather than
/// being created inline with `TcpStream::connect`, so tests can inject an
/// in-memory `tokio::io::duplex()` half — or a future that fails — and
/// observe the handshake behaviour without touching the network.
///
/// On handshake failure the client address is logged (scrubbed) and a typed
/// error is returned; the function never panics on a dial or handshake
/// error reachable from the network.
///
/// # Cancel safety
///
/// cancel-safe: NO — `establish` runs the obfs4/webtunnel handshake, which
/// writes to the underlying socket. Dropping this future mid-handshake can
/// leave the peer expecting bytes that were never sent. The caller
/// (`client_handle_connection`) runs inside a dedicated `tokio::spawn` task,
/// so it is not composed under a `select!`/`timeout` cancellation point.
pub(crate) async fn establish_pt_conn<In2, C2>(
    pt_client: C2,
    dial: Pin<ptrs::FutureResult<In2, std::io::Error>>,
    client_addr: SocketAddr,
) -> Result<C2::OutRW>
where
    // The dialed socket must be usable as an async connection. These are the
    // same bounds the transport traits require of their `InRW` parameter.
    In2: AsyncRead + AsyncWrite + Send + Sync + Unpin + 'static,
    C2: ptrs::ClientTransport<In2, std::io::Error> + Send,
{
    match ptrs::ClientTransport::<In2, std::io::Error>::establish(pt_client, dial).await {
        Err(e) => {
            warn!(
                address = sensitive(client_addr).to_string(),
                "handshake failed: {e:#?}"
            );
            Err(obfs4::Error::from(e.to_string())).context("handshake failed")
        }
        Ok(c) => Ok(c),
    }
}

mod server;
#[cfg(feature = "experimental-server")]
use server::server_setup;

// ================================================================ //
//        PT-spec helpers (auth, args, parent-channel messages)     //
// ================================================================ //

/// Custom `fast_socks5` authenticator. Per pt-spec §3.5 the parent
/// MUST negotiate USERNAME/PASSWORD when it wants to pass per-bridge PT
/// args; we accept any (or no) credentials and just propagate them so
/// `client_handle_connection` can grab them via `take_credentials()`.
#[derive(Clone, Copy, Default)]
struct PtArgsAuth;

#[async_trait::async_trait]
impl fast_socks5::server::Authentication for PtArgsAuth {
    type Item = (String, String);

    async fn authenticate(&self, credentials: Option<(String, String)>) -> Option<Self::Item> {
        // Propagate creds untouched. `None` (NO_AUTH path) is also fine —
        // we let it through as empty strings so the same plumbing applies.
        Some(credentials.unwrap_or_default())
    }
}

/// Reconstruct the PT-spec argument string from the SOCKS5
/// USERNAME/PASSWORD fields, mirroring Go lyrebird `rfc1929.go:88-100`.
///
/// PT spec §3.5 mandates this peculiar split when the arg string
/// exceeds 255 bytes: the parent process packs it into
/// `(username, password)` with `username` capped at 255 bytes.
///
/// * `passwd == [0x00]` is the "no passwd; uname is the whole arg list"
///   marker — return just `uname`.
/// * Otherwise concatenate `uname` and `passwd` as raw bytes, no
///   separator.
/// * `None` means the client connected via NO_AUTH (no args).
pub fn arg_string_from_creds(creds: Option<(String, String)>) -> String {
    match creds {
        None => String::new(),
        Some((uname, passwd)) if passwd.as_bytes() == [0x00] => uname,
        Some((uname, passwd)) => {
            let mut s = uname;
            s.push_str(&passwd);
            s
        }
    }
}

/// Minimal subset of the PT spec's parent-channel protocol (the lines
/// the PT prints on stdout for `tor`/`arti` to read). Without these
/// arti waits forever and reports "PT binary gone".
mod pt_proto;

#[cfg(test)]
mod tests;
